name: Anya Spethmann
favicon: null
layout_spectrum: 0.2706093
typography_spectrum: 0.6003584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b5e1fd'
    - '#16160e'
    - '#758cb2'
    - '#fefefc'
    - '#c4836b'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
