layout_spectrum: 0.2706093
color:
  saturation: 0.9946272
  brandStrength: 0.06239344
  lightness: 0.05289543
  rhythmicContrast: 0.6290323
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.6003584
name: Anya Spethmann
